### PR TITLE
Add setPrimaryByDelegateCash

### PR DESCRIPTION
**Pull request by 0xtiby**
@PirateCode-eth 

Here's what I do :  if user select delegate cash, I fetch all his delegation and extract all vaults addresses. Next I call the backend to get nfts from all vaults. Potential drawback if user has a lots of vaults maybe we can hit some rate limit on Alchemy api.

### CODE REVIEW

**Comment by PirateCode-eth** [comment]
> @PirateCode-eth
> 
> Here's what I do : if user select delegate cash, I fetch all his delegation and extract all vaults addresses. Next I call the backend to get nfts from all vaults. Potential drawback if user has a lots of vaults maybe we can hit some rate limit on Alchemy api.

I think we can filter the NFTs by [isVerified](https://github.com/ForeverPFP/pfp-verification-contract/blob/main/src/IPFPVerification.sol#L35) or [getVerifiedCollections](https://github.com/ForeverPFP/pfp-verification-contract/blob/main/src/IPFPVerification.sol#L40) from pfp-verification-contract because most of the NFTs are not for PFP or junk, like ENS will be shown there which is NFT but sure not PFP. And if user want to set the collection that is not verified, they can enter the collection contract address and tokenId by themselves.

But we can merge this first.

**Review by PirateCode-eth — APPROVED** [review]
LGTM

**Comment by PirateCode-eth** [comment]
I think when user select the delegate cash, we only need to fetch the delegated NFTs, no need to fetch NFTs in user current connected wallet?

**Comment by 0xtiby** [comment]
Yes when delegate cash selected I only fetch from vaults delegated to the wallet connected.

**Comment by PirateCode-eth** [comment]
I mean that maybe wrong.

Delegate.cash have 3 level of delegation: token, contract and wallet.

Only wallet delegation required fetch all the NFT from vault, if contract
delegation we only need fetch NFTs in one contract, if token delegation we
only need fetch token.

If the NFTs are not delegated in any one of these delegation, the
setPrimaryFromDelegateCash function won’t work.

**Comment by 0xtiby** [comment]
Yes but imagine if the user as delegated one token for a mutant and one token for a ape. It should be able to choose both even if they come from two differents contracts. 

As I fetch everything from all addresses which are delegated your code will always work because you tried for every method.
`dci.checkDelegateForToken , dci.checkDelegateForContract, dic.checkDelegateForAll`

I show only from delegation

**Comment by PirateCode-eth** [comment]
But when I tried the delegate.cash check, the UI showed not only delegated
PFPs, but also the PFPs that not delegated but in the address?

**Comment by 0xtiby** [comment]
Ho I think it's a bug this shouldn't happen. I opened this https://github.com/ForeverPFP/primary-pfp-frontend/issues/24

**Comment by PirateCode-eth** [comment]
Got it.

**Pull request merged**
