### PR TITLE
Add warm.xyz / Hide Step 4 and 5

### PR DESCRIPTION
**Pull request by 0xtiby**

### CODE REVIEW

**Comment by 0xtiby** [comment]
@PirateCode-eth

**Review by PirateCode-eth — APPROVED** [review]
LGTM

**Comment by PirateCode-eth** [comment]
when I choose the delegate.cash, still showing all my wallet NFTs?

**Comment by 0xtiby** [comment]
Did you try with the preview from vercel ? 
Look on my side https://www.loom.com/share/49201314e1fe4324902b505bea106409 work correctly. 
Really weird

**Comment by PirateCode-eth** [comment]
> Did you try with the preview from vercel ? Look on my side https://www.loom.com/share/49201314e1fe4324902b505bea106409 work correctly. Really weird

can you try my address? 0x200D26209144498Aac957F8a55B0Bb980673bdD8
image
image

and I didn't delegate my address:
image

**Comment by 0xtiby** [comment]
Ok I found the issue you have delegate this 

image

But on my side what I do is getDelegationsByDelegate and then I take all the vault addresses returned, deduplicate them and next fetch all nfts from wallets. 

AS your vault's and hot wallet are the same that why you get the same list.

And there's something here to discuss I think with delegate you can pretty much what you want : 
Like delegate the same vault to the same hot wallet with different type of delegation like ALL and CONTRACT level. 

In this case I don't know the rule to apply. 

Maye I can do something like this : 

I do the same thing as now (get all address, fetch nfts) and then after I don't show nft that are not in delegations. 

Image something like this : 
User use a hot wallet named C with this delegation list :

- Delegate for all wallet A 
- Delegate for contract 0xB wallet B
- Delegate for token 12 contract 0xD wallet B

I will fetch all nfts from wallet A,B,C and then show : 
- all nft of wallet A
- all nft of contract 0xB owned by the user 
- nft 12 of contract 0xD

**Comment by PirateCode-eth** [comment]
I think the key point is if I only delegate token 2300, then if I called the function setPrimaryByDelegateCash with other NFTs that I didn't delegate, it will report error. 

So when user select set primary be delegate cash, we only need to those the NFTs that had been delegated by the wallet.
 
No need to show all the NFTs in that wallet.

**Comment by PirateCode-eth** [comment]
I need to explain it more, why make new function for delegation instead of check delegation in set primary in one function.

Because if we check all the delegations by delegate.cash and warm.xyz mixed with the set owner by the wallet, it make cost more gas for both of these 3 types of users, because the check logic is more, that's why I made them to three different functions to save gas by their own choices.

**Comment by 0xtiby** [comment]
> 

Yes I understand that we need to not show all nfts because it will fail in the tx if we let the user choose something that's not delegated. 

It's just that delegate.cash allow to delegate in differents way on differents token, contract etc.. And I only have the possibility to fetch nft's by addresses.  So I will always fetch all nft's from vaults and then show it or not based on the delegations.

Maybe I don't explain myself correctly. I will fix this. 
At least we have found the issue

**Comment by PirateCode-eth** [comment]
LFG.

**Pull request merged**
